version: '3.8'

services:
  career-craft-sqlite:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_PROVIDER=sqlite
      - DATABASE_URL=file:/app/data/dev.db
      - NEXTAUTH_SECRET=your-production-secret-key-here
      - NEXTAUTH_URL=http://localhost:3000
      - DISABLE_USER_REGISTRATION=true
      - NODE_ENV=production
      - UPLOADS_DIR=/app/public/uploads
    volumes:
      - sqlite_data:/app/data
      - uploads_data:/app/public/uploads
    restart: unless-stopped

volumes:
  sqlite_data:
  uploads_data:
