version: '3.8'

services:
  # SQLite version (default - simpler setup)
  career-craft-sqlite:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_PROVIDER=sqlite
      - DATABASE_URL=file:/app/data/dev.db
      - NEXTAUTH_SECRET=your-production-secret-key-here
      - NEXTAUTH_URL=http://localhost:3000
      - NODE_ENV=production
      - UPLOADS_DIR=/app/public/uploads
    volumes:
      - sqlite_data:/app/data
      - uploads_data:/app/public/uploads
    restart: unless-stopped

  # PostgreSQL version (recommended for production)
  career-craft-postgres:
    build: .
    ports:
      - "3001:3000"
    environment:
      - DATABASE_PROVIDER=postgresql
      - DATABASE_URL=postgresql://personal_crm:password@postgres:5432/personal_crm
      - NEXTAUTH_SECRET=your-production-secret-key-here
      - NEXTAUTH_URL=http://localhost:3001
      - NODE_ENV=production
      - UPLOADS_DIR=/app/public/uploads
    depends_on:
      - postgres
    volumes:
      - uploads_data:/app/public/uploads
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=personal_crm
      - POSTGRES_USER=personal_crm
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  sqlite_data:
  postgres_data:
  uploads_data:
